import Footer from "@/projects/artistry-hub/common/footer";
import Header from "@/projects/artistry-hub/common/header";
import { Inter } from "next/font/google";
// import "./globals.css";
// import StoreProvider from "./storeProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ArtistryHubLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <StoreProvider> */}
            <Header/>
          {children}
          <Footer/>
        {/* </StoreProvider> */}
     </body>
    </html>
  );
}

export const layoutChildren=<ArtistryHubLayout/>
