import { Inter } from "next/font/google";
// import "./globals.css";
// import StoreProvider from "./storeProvider";
import Header from "@/projects/trend-chic-app/common/header";
import Footer from "@/projects/trend-chic-app/common/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function TrendChickLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <StoreProvider> */}
            <Header/>
          {children}
          <Footer/>
        {/* </StoreProvider> */}
     </body>
    </html>
  );
}

export const layoutChildren=<TrendChickLayout/>
